### PR TITLE
Added Search Tests

### PR DESCRIPTION
**Pull request by IsmailBourbie**
# note: 
You should create another database named 'laravel_test'

### CODE REVIEW

**Comment by theHocineSaad** [comment]
Thanks Ismail,
For your note about 'laravel_test' db, please check: [c1d1631](https://github.com/theHocineSaad/linatabra3/pull/7/commits/c1d163114ed2162857ec8a90565c02394e9feac2)

**Comment by IsmailBourbie** [comment]
> please check: [c1d1631](https://github.com/theHocineSaad/linatabra3/pull/7/commits/c1d163114ed2162857ec8a90565c02394e9feac2)

I think there is something wrong; what you did exactly is testing with the real production database and not the in-memory database; if we want to use the In-Memory Implementation, we should include the subsequent lines in `phpunit.xml`:

```xml
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>
```

**Comment by theHocineSaad** [comment]
Thanks @IsmailBourbie for the notice.
I thought not specifying a DB_DATABASE, will default to use In-Memory database, but I was wrong.
Fixed it here: 34d86db83f9a28f098bad4f5f0afb9b5f1b677f7

**Comment by IsmailBourbie** [comment]
> Fixed it here: 34d86db83f9a28f098bad4f5f0afb9b5f1b677f7

Be careful about **seeding database** in your tests because it takes more time, that's why i preferred `DB::truncate()` for now.

**Comment by theHocineSaad** [comment]
> runcat

How can truncate() replace seeding the database? can you please explain.
truncate() will just empty the table and reset the auto increment.
And for example, the "it_can_search_with_blood_group_only" test is calling the function "search" from "DonorController" which is interacting with the "blood_groups" table, so we do need to seed this table in that case.
I hope you got it, please tell me if I'm wrong.

**Comment by IsmailBourbie** [comment]
> How can truncate() replace seeding the database? can you please explain.

Actually It's not replacing it, what I do I just seed the database when I create it at the first time using `tinker`, and then in my tests just truncate only `users` table.

**Comment by theHocineSaad** [comment]
> e

Understood.
For your comment about seeding database takes more time, for now, it's not taking so much time, it's almost the same, maybe because the database is on memory.
Please tell me if this is still wrong.

**Pull request merged**
