### PR TITLE
DonorsController refactoring

### PR DESCRIPTION
**Pull request by IsmailBourbie**
Removing duplication in Search action.
improving request time by reducing SQL queries.

## before: 
image

## after:
image

### CODE REVIEW

**Comment by theHocineSaad** [comment]
looks like the code you contributed in [42fe979](https://github.com/theHocineSaad/linatabra3/pull/8/commits/42fe979df41d8f40e2f94662153aa3ae3d087c9c) in not working properly, please have a second look at it and retest it.

**Comment by IsmailBourbie** [comment]
> looks like the code you contributed in [42fe979](https://github.com/theHocineSaad/linatabra3/pull/8/commits/42fe979df41d8f40e2f94662153aa3ae3d087c9c) in not working properly, please have a second look at it and retest it.

Can you please give me more details, and tell what's wrong exactly?

**Comment by theHocineSaad** [comment]
> tell w

Your code in fine, It's just me getting wrong results because of the Test that was running in the main database, my bad.
Just one more thing, you can ignore checking if $filters['blood_group'] (in app\Models\User.php - line 51) exists, it will always exist, because of the validation in DonorRequest (in app\Http\Controllers\DonorController.php - line 22).

**Comment by IsmailBourbie** [comment]
> Just one more thing, you can ignore checking if $filters['blood_group'] (in app\Models\User.php - line 51) exists, it will always exist, because of the validation in DonorRequest (in app\Http\Controllers\DonorController.php - line 22).

Yes you can ignore checking for now, but am planning to delete Search feature and replace it with **Filters** in `DonorsController::index`, for exmaple:

```php

// using DonorsController::index
linatabra3.com/donors // get all donors 
linatabra3.com/donors?blood_group=1 // get all donors with donors_group = 1
linatabra3.com/donors?blood_group=1&wilaya=1 // get all donors with donors_group = 1 and wilaya = 1
```
## instead of:

```php

// using DonorsController::index and DonorsController::search
linatabra3.com/donors // get all donors
linatabra3.com/donors/search?blood_group=1 // get all donors with donors_group = 1
linatabra3.com/donors/search?blood_group=1&wilaya=1 // get all donors with donors_group = 1 and wilaya = 1
```

**Comment by theHocineSaad** [comment]
> ```
> h?bloo
> ```

Okay, good idea.
Thanks for your contributions

**Pull request merged**
